### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by GOGO98901** [GOGO98901/Lost#17]
I managed to get and build working locally (again)
however I now get this error
```java
[java] WARNING: Sound not loaded 'footstep-01.wav' 
[java] WARNING: java.lang.NullPointerException
[java] 	at org.newdawn.slick.Sound.<init>(Sound.java:56)
[java] 	at net.roryclaasen.lost.soundengine.Sound.<init>(Unknown Source)
[java] 	at net.roryclaasen.lost.soundengine.SoundManager.loadSound(Unknown Source)
[java] 	at net.roryclaasen.lost.soundengine.SoundManager.loadAll(Unknown Source)
[java] 	at net.roryclaasen.lost.soundengine.SoundManager.<init>(Unknown Source)
[java] 	at net.roryclaasen.lost.GameThread.init(Unknown Source)
[java] 	at net.roryclaasen.Bootstrap.start(Unknown Source)
[java] 	at net.roryclaasen.Bootstrap.main(Unknown Source)
```
Full log file -> [latest.log](https://github.com/GOGO98901/Lost/files/74339/latest.log.txt)

**Comment by GOGO98901** [comment]
Fixed in 30030fe
